["pyproject.toml".tool.poetry.dependencies]
python = "^3.11"

["pyproject.toml".tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.2.0"
nitpick = "^0.33.1"
wemake-python-styleguide = "^0.17.0"
